version: '3.8'

networks:
  CSEC:
    driver: bridge

volumes:
  grafana-storage: {}

services:
## ----------------------------- DASHBOARD ---------------------------
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
     - '3000:3000'
    volumes:
     - grafana-storage:/var/lib/grafana
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - CSEC

## ------------------------- DASHBOARD END ----------------------------   

## ---------------------------- DATABASE ------------------------------
  postgres:
    image: postgres:12.10
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: csec
      POSTGRES_PASSWORD: csec
      POSTGRES_DB: csec_db
    networks:
      - CSEC

  pg_admin:
    image: dpage/pgadmin4
    container_name: pg_admin
    restart: always
    ports:
      - '3031:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: csec@csec.us
      PGADMIN_DEFAULT_PASSWORD: csec
    links:
      - postgres
    networks:
     - CSEC

## -------------------------- DATABASE END --------------------------

## -------------------------- DATA ROUTING --------------------------
  nifi:
    image: apache/nifi
    container_name: nifi
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - '8080:8080/tcp' # HTTP interface
      - '8443:8443/tcp' # HTTPS interface
      - '514:514/tcp' # Syslog
      - '514:514/udp' # Syslog
      - '2055:2055/udp' # NetFlow
    environment:
      NIFI_WEB_HTTP_PORT: 8080
    expose:
      - 8080
    networks:
     - CSEC

## ---------------------- DATA ROUTING END -------------------------